#!/bin/bash

set -x

# Disable Redis protected mode [1] as it is unnecessary in context of Docker
# (ports are not automatically exposed when running inside Docker, but rather explicitly by specifying -p / -P)
# [1]: https://github.com/redis/redis/commit/edd4d555df57dc84265fdfb4ef59a4678832f6da

cp redis-7.2.patch /usr/src/redis/

cd /usr/src/redis
patch -p1 -i redis-7.2.patch

# For future reference, we modify this directly in the source instead of just supplying a default
# configuration flag because apparently "if you specify any argument to redis-server, 
# [it assumes] you are going to specify everything".
# See also https://github.com/docker-library/redis/issues/4#issuecomment-50780840
# (more exactly, this makes sure the default behavior of "save on SIGTERM" stays functional by default)
