#!/bin/bash

# disable Redis protected mode [1] as it is unnecessary in context of Docker
# (ports are not automatically exposed when running inside Docker, but rather explicitly by specifying -p / -P)
# [1]: https://github.com/redis/redis/commit/edd4d555df57dc84265fdfb4ef59a4678832f6da
# for future reference, we modify this directly in the source instead of just supplying a default configuration flag
# because apparently "if you specify any argument to redis-server, [it assumes] you are going to specify everything"
# see also https://github.com/docker-library/redis/issues/4#issuecomment-50780840
# (more exactly, this makes sure the default behavior of "save on SIGTERM" stays functional by default)

grep -q '^#define CONFIG_DEFAULT_PROTECTED_MODE 1$' src/redis/src/server.h
sed -ri 's!^(#define CONFIG_DEFAULT_PROTECTED_MODE) 1$!\1 0!' src/redis/src/server.h
grep -q '^#define CONFIG_DEFAULT_PROTECTED_MODE 0$' src/redis/src/server.h

git --no-pager diff -p > redis.patch
