#!/bin/bash

# https://github.com/jemalloc/jemalloc/issues/467 -- we need to patch the "./configure" for the bundled jemalloc to match how Debian compiles, for compatibility
# (also, we do cross-builds, so we need to embed the appropriate "--build=xxx" values to that "./configure" invocation)

gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"
extraJemallocConfigureFlags="--build=$gnuArch"

# https://salsa.debian.org/debian/jemalloc/-/blob/c0a88c37a551be7d12e4863435365c9a6a51525f/debian/rules#L8-23
dpkgArch="$(dpkg --print-architecture)"
case "${dpkgArch##*-}" in
  amd64 | i386 | x32)
    extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=12"
	;;
  *)
    extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=16"
	;;
esac
extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-hugepage=21"
grep -F 'cd jemalloc && ./configure ' /usr/src/redis/deps/Makefile
sed -ri 's!cd jemalloc && ./configure !&'"$extraJemallocConfigureFlags"' !' /usr/src/redis/deps/Makefile
grep -F "cd jemalloc && ./configure $extraJemallocConfigureFlags " /usr/src/redis/deps/Makefile
