name: Pull Request Build and Test

on:
  pull_request:
    branches:
      - master
      - release/*
      - unstable

jobs:
  validate-dockerfiles-synced:
    name: Validate Dockerfiles Synced
    runs-on: ubuntu-latest
    steps:
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@27de2ed8de16af5270d32003a4c8bfc3c54e0a20
        with:
          customer-id: sha5oz2y
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: administrator
          profile-region: us-east-1
          async: true
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Validate Dockerfiles are synced with templates
        uses: ./.github/actions/validate-dockerfiles-synced

  build-and-test:
    needs: validate-dockerfiles-synced
    uses: ./.github/workflows/build-n-test.yml
    if: github.event_name == 'pull_request' && github.base_ref != 'unstable'
    secrets: inherit
    with:
      release_tag: ''
      publish_image: false
      run_type: pr

  build-and-test-unstable:
    needs: validate-dockerfiles-synced
    uses: ./.github/workflows/build-n-test.yml
    if: github.event_name == 'pull_request' && github.base_ref == 'unstable'
    secrets: inherit
    with:
      release_tag: unstable
      publish_image: false
      redisearch_version: master
      redisjson_version: master
      redisbloom_version: master
      redistimeseries_version: master
      run_type: unstable
