name: Test Nightly Unstable Build and Package
on:
  schedule:
    - cron: '0 11 * * *'  # Run every day at 11:00 AM UTC
  push:
    branches:
      - unstable-alignment

jobs:
  build-and-test-unstable:
    uses: redis/docker-library-redis/.github/workflows/pre-merge.yml@unstable-alignment
    with:
      release_tag: unstable
      redisearch_version: master
      redisjson_version: master
      redisbloom_version: master
      redistimeseries_version: master
      publish_image: true
      custom_build: branch
      run_type: nightly